### ISSUE TITLE
Crash issue with dragon block c animations

### ISSUE THREAD

**Issue by reuben-matus** [makamys/CoreTweaks#11] opened 2023-02-23 09:22 UTC
Upon playing the crashing animation I am faced with this crash (tried disabling bug fixes, optimizations and tweaks 1 by 1 and still didn't work)
(I remove the mod and the game runs fine)
[crash-2023-02-23_20.16.37-client.txt](https://github.com/makamys/CoreTweaks/files/10812038/crash-2023-02-23_20.16.37-client.txt)

**Comment by makamys** [comment] 2023-02-23 10:28
Based on the log this was caused by an issue in the `fix_entity_tracking` module. Can you check if it's fixed in this build?
https://github.com/makamys/CoreTweaks/suites/11155799462/artifacts/569415801

**Comment by reuben-matus** [comment] 2023-02-23 16:19
Yep, that fixes the issue thank you 🙏

**Closed** 2023-02-23 17:05 UTC

**Comment by makamys** [comment] 2023-02-23 17:11
> for some reason I experience a performance drop when using the mod as opposed to an increase though :/

Strange, I wonder if it's also caused by `fix_entity_tracking`?

**Comment by reuben-matus** [comment] 2023-02-24 23:34
I disabled the setting and it still caused lag spikes for some reason as opposed to normally smooth gameplay :/

**Comment by makamys** [comment] 2023-02-25 22:48
I'm not getting any lag spikes, so this is probably an incompatibility with one of your mods. Can you send me some profiler snapshots? One with and one without CoreTweaks, for comparison. You can use spark or VisualVM for this. The frametime graph in [Sampler](https://www.curseforge.com/minecraft/mc-mods/sampler)'s F3 overlay can also help to easily identify when the lag spikes happen.
