### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by Mobius0526** [makamys/CoreTweaks#25] opened 2023-12-18 01:44 UTC
[crash-2023-12-18_09.33.59-client.txt](https://github.com/makamys/CoreTweaks/files/13698644/crash-2023-12-18_09.33.59-client.txt)
The same configuration will not crash on Windows

**Comment by makamys** [comment] 2023-12-18 04:53
I managed to reproduce this by what appears to be a complete coincidence. In my case my `scala-compiler-2.11.1.jar` was corrupted, which caused `fast_default_resource_pack` to crash even if no mods other than CoreTweaks are present.

I added some error handling which should make it not crash anymore. Let me know if it works. You can grab the new build here: https://github.com/makamys/CoreTweaks/actions/runs/7243737485/artifacts/1120555046

And if you want to figure out what jar is corrupted, disable `forge_mod_discoverer_skip_known_libraries` and you should see an error like this:
```
[Client thread/WARN] [FML]: Zip file scala-compiler-2.11.1.jar failed to read properly, it will be ignored
```

**Comment by Mobius0526** [comment] 2023-12-18 05:49
yes，My scala-compiler-2.11.1.jar is also corrupted，
After updating CoreTweeks, I can start the game
After entering the save, the leaves, grass, many blocks, and most of the items in my backpack were flashing wildly，The method of refreshing the world by modifying language or resource pack settings can make the world normal

**Comment by makamys** [comment] 2023-12-18 06:31
Alright, I'll close this since the original issue is fixed. The flashing sounds like an unrelated issue that may not even be caused by CoreTweaks. But do open a new issue if you can confirm that it is.

**Closed by makamys** 2023-12-18 06:31 UTC
