### ISSUE TITLE
0.3.1 causes crash.

### ISSUE THREAD

**Issue by MagmaBro123** [makamys/CoreTweaks#19] opened 2023-10-24 17:05 UTC
Title.

https://pastebin.com/hVTnhvqC

Something about 'com/jcraft/jorbis/StaticCodeBook', whatever this is.

**Comment by makamys** [comment] 2023-10-24 17:13
You'll have to post the full log (`fml-client-latest.log` probably). Also, did you check that it doesn't happen with 0.3.0.4?

**Comment by MagmaBro123** [comment] 2023-10-24 17:21
No crash with 0.3.0.4.

[fml-client-latest.log](https://github.com/makamys/CoreTweaks/files/13121923/fml-client-latest.log)

**Comment by makamys** [comment] 2023-10-24 18:46
Not quite sure why this happens and I couldn't reproduce it, but I pushed a commit that might fix it. Can you try it and post a log again (regardless of whether it crashes or not)?

**Comment by MagmaBro123** [comment] 2023-10-24 18:53
Yep, game loads to main menu and doesn't crash.

**Comment by makamys** [comment] 2023-10-24 18:58
And the log?

**Comment by MagmaBro123** [comment] 2023-10-24 19:04
Nothing in the log.

**Comment by makamys** [comment] 2023-10-24 19:36
Yeah, but can you post it? I need to see it myself to verify that the fix worked.

**Comment by MagmaBro123** [comment] 2023-10-24 19:39
Ah, sorry then.

This is in a modpack btw, but the crash report I gave before mentions 'com/jcraft/jorbis/StaticCodeBook', which I have no clue which mod that's from.

But here's the log.

[fml-client-latest.log](https://github.com/makamys/CoreTweaks/files/13126612/fml-client-latest.log)

**Comment by makamys** [comment] 2023-10-24 19:51
> Dropping cpw.mods.fml.common.asm.transformers.TerminalTransformer from cache because we don't care about it anymore.

That's strange, did you change the `transformersToCache` config option? Your log implies that caching was turned off for all transformers.

> I have no clue which mod that's from

Jorbis is a sound library vanilla comes with, the error happened while loading one of its classes, not sure why though.

**Comment by MagmaBro123** [comment] 2023-10-24 20:01
> > Dropping cpw.mods.fml.common.asm.transformers.TerminalTransformer from cache because we don't care about it anymore.
> 
> That's strange, did you change the `transformersToCache` config option? Your log implies that caching was turned off for all transformers.
> 
> > I have no clue which mod that's from
> 
> Jorbis is a sound library vanilla comes with, the error happened while loading one of its classes, not sure why though.

No, default config.

**Comment by makamys** [comment] 2023-10-24 20:37
Oh. Okay, that message is because of a separate bug, that one's on me. It shows up every time, and nothing actually gets dropped when it gets printed.

So there's just one more thing, can you delete your `coretweaks/cache/classTransformerLite.cache` and re-run the game and post the log of that run? I want to see what happens when the cache first gets constructed.

**Comment by MagmaBro123** [comment] 2023-10-24 20:44
No classTransformerLite.cache exists.

[fml-client-latest.log](https://github.com/makamys/CoreTweaks/files/13127244/fml-client-latest.log)

**Comment by makamys** [comment] 2023-10-24 20:52
Odd, are you perhaps using the "Kill" button to close the game instead of closing it normally?

**Comment by MagmaBro123** [comment] 2023-10-24 20:53
The game crashes as soon as I open it, the Back to main menu button just closes the game.

**Comment by makamys** [comment] 2023-10-24 20:54
There's a crash? I thought you said

> Yep, game loads to main menu and doesn't crash.

**Comment by MagmaBro123** [comment] 2023-10-24 20:55
3.0.1 causes the crash, the one from the Actions tab doesn't.

**Comment by makamys** [comment] 2023-10-24 21:06
Well, what I was asking is if you were closing the game properly while using the Actions build. The cache only gets saved when the game shuts down cleanly, so if you were killing it, that would explain why it's not there.

**Comment by MagmaBro123** [comment] 2023-10-24 21:08
> Well, what I was asking is if you were closing the game properly while using the Actions build. The cache only gets saved when the game shuts down cleanly, so if you were killing it, that would explain why it's not there.

Ah, whoops. Since the doesn't crash I can close it just fine, I didn't Task Manager kill it or anything.

**Comment by makamys** [comment] 2023-10-24 21:14
Okay, try clicking the "Quit Game" button on the main menu and see if the cache file appears.

**Comment by MagmaBro123** [comment] 2023-10-24 21:15
OH. Huh... Now it created the file...

[fml-client-latest.log](https://github.com/makamys/CoreTweaks/files/13127505/fml-client-latest.log)

![image](https://github.com/makamys/CoreTweaks/assets/51277766/36f84821-872a-4589-b12a-ce05facd29c3)

**Comment by makamys** [comment] 2023-10-24 21:54
There we go, I'm guessing you were pressing Prism's "Kill" button without realizing.

Anyway, I looked at your logs again and noticed something... You switched modpacks after the first log! The first one was in an instance called "1.7.10", and the second one was in "LOTR The Forgotten Ages", with a different set of mods. So the results are inconclusive. The crash most likely disappeared because you switched modpacks, not because you updated CoreTweaks.

I need you to test the Actions build in the "1.7.10" pack, *where the crash happened*, and send me a log of the run. (And sorry for asking for so many logs, but since I can't reproduce the issue, it's the only way I have of troubleshooting it.) Also I pushed [a new commit](https://github.com/makamys/CoreTweaks/actions/runs/6631189385) with some improvements to logging.

**Comment by MagmaBro123** [comment] 2023-10-24 22:58
[fml-client-latest.log](https://github.com/makamys/CoreTweaks/files/13129473/fml-client-latest.log)

Sorry for being confusing if I am.

**Comment by makamys** [comment] 2023-10-25 08:44
I meant test the Actions build (`0.3.1-3-g3f1a035`), we already know 0.3.1 crashes.

And yeah, I was testing in production with Dynamic Surroundings + Sound Filters + Aether II, but no dice.

**Comment by MagmaBro123** [comment] 2023-10-25 17:54
Well, the builds you did somehow work, so.

**Comment by makamys** [comment] 2023-10-26 05:04
Again, I asked you to post a log.

**Comment by MagmaBro123** [comment] 2023-10-26 06:04
Already did, https://github.com/makamys/CoreTweaks/issues/19#issuecomment-1778184867

**Comment by makamys** [comment] 2023-10-26 06:12
I mean a log with `0.3.1-3-g3f1a035` in the "1.7.10" instance where the crash in the first post happened.

**Comment by MagmaBro123** [comment] 2023-10-26 06:42
Ah, whoops.

[fml-client-latest.log](https://github.com/makamys/CoreTweaks/files/13173775/fml-client-latest.log)

**Comment by makamys** [comment] 2023-10-26 06:45
That looks fine, now I just need a log after deleting `classTransformerLite.cache` (In the same instance with the same mods)

**Comment by MagmaBro123** [comment] 2023-10-26 17:17
[fml-client-latest.log](https://github.com/makamys/CoreTweaks/files/13180618/fml-client-latest.log)

**Comment by makamys** [comment] 2023-10-27 12:00
Thanks, that should be the last one I'll need.

I managed to reproduce it now in dev with no other mods by a stroke of luck, but it's very rare. I also found a way to consistently cause it to happen with development tools.

It's a race condition that happens when the thread gets interrupted while a diff is being generated. In your case this happened on the sound command thread. Since it's a rare issue, simply quietly ignoring the error and trying again on the next run is a valid solution, which I just implemented.

<details>
<summary>How to reproduce it</summary>

0. Disable music
1. Add the following breakpoints:
  - `Thread#interrupt`
  - `CommandThread#run`, line 112 (`soundSystem.CommandQueue( null );`)
  - `Channels$ReadableByteChannelImpl#read`, line 385 (`bytesRead = in.read(buf, 0, bytesToRead);`), with the following condition: `!Thread.currentThread().getName().contains("Client")`
2. Disable all breakpoints and launch the game
3. Once you're on the main menu, enable breakpoints
4. Click a button
5. You will hit the interrupt breakpoint on the main thread, continue that thread
6. You will hit the CommandThread breakpoint on the command thread, continue that thread
7. You will hit the Channels breakpoint on the command thread, continue **the main thread**
8. Disable all breakpoints and continue the game
</details>

**Closed by makamys** 2023-10-27 12:00 UTC

**Comment by MagmaBro123** [comment] 2023-10-27 18:44
Sorry for the confusion, didn't know which log files you needed before.

**Comment by makamys** [comment] 2023-10-27 19:01
I find that highly unlikely, are you sure this only happens with CoreTweaks?

**Comment by MagmaBro123** [comment] 2023-10-27 19:44
Apparently LUMINA (a FalsePattern mod) is the issue. 'fix_heightmap_range' has to be disabled (ometimes it causes this or just crashes).

**Comment by makamys** [comment] 2023-10-27 20:06
I see, I also get a crash with it. I'll just make my mixin get disabled if LUMINA is detected, since I assume it's unnecessary anyway, being another lighting fix.

**Comment by MagmaBro123** [comment] 2023-10-27 20:23
Apparently TCLPrject's Particle Distance Increaser mod is what causes the invisible world issue. So that's figured out.

**Comment by makamys** [comment] 2023-10-27 20:35
I can't find a mod by that name, do you mean [Entity Render Distance Extender](https://legacy.curseforge.com/minecraft/mc-mods/entity-render-distance-extender)?

**Comment by MagmaBro123** [comment] 2023-10-27 22:10
https://www.curseforge.com/minecraft/mc-mods/increase-particle-distance
