### ISSUE TITLE
fast_default_resource_pack caused crash

### ISSUE THREAD

**Issue by Tree-er233** [makamys/CoreTweaks#26] opened 2023-12-18 05:48 UTC
I have installed CoreTweaks-1.7.10-0.3.3.1+nomixin
When I disable this option, the crash no longer occurs.
Here is a log
[fml-client-latest.log](https://github.com/makamys/CoreTweaks/files/13699747/fml-client-latest.log)
I'm not sure what's causing this issue，could you please fix this issue or tell me what I should do next?🙂

**Comment by makamys** [comment] 2023-12-18 06:32
This sounds like a duplicate of #25, which should be fixed as of 0.3.3.2 (which was just released). Try updating.

**Comment by Tree-er233** [comment] 2023-12-18 06:46
Yes, the new version fixes the issue and the game now launches properly.

**Closed** 2023-12-18 07:24 UTC
